### ISSUE TITLE
Ruby 1.8.7 compatiblity

### ISSUE THREAD

**Issue by Klaas-** [govdelivery/infoblox#30]
Hi :)
with the changes to get the gem compatible with ruby 1.8.7 I get the following error (both 1.9.3 and 1.8.7) when trying to use a connection
```
Faraday::ConnectionFailed: 403 "Forbidden"
        from /opt/rh/ruby193/root/usr/share/ruby/net/http.rb:2633:in `error!'
        from /opt/rh/ruby193/root/usr/share/ruby/net/http.rb:2642:in `value'
        from /opt/rh/ruby193/root/usr/share/ruby/net/http.rb:796:in `connect'
        from /opt/rh/ruby193/root/usr/share/ruby/net/http.rb:756:in `do_start'
        from /opt/rh/ruby193/root/usr/share/ruby/net/http.rb:745:in `start'
        from /opt/rh/ruby193/root/usr/share/ruby/net/http.rb:1285:in `request'
        from /opt/rh/ruby193/root/usr/share/ruby/net/http.rb:1027:in `get'
        from /opt/rh/ruby193/root/usr/local/share/gems/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:80:in `perform_request'
        from /opt/rh/ruby193/root/usr/local/share/gems/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
        from /opt/rh/ruby193/root/usr/local/share/gems/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
        from /opt/rh/ruby193/root/usr/local/share/gems/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
        from /opt/rh/ruby193/root/usr/local/share/gems/gems/faraday_middleware-0.9.1/lib/faraday_middleware/request/encode_json.rb:23:in `call'
        from /opt/rh/ruby193/root/usr/local/share/gems/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
        from /opt/rh/ruby193/root/usr/local/share/gems/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
        from /opt/rh/ruby193/root/usr/local/share/gems/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
        from /app/app/home/gemtest/.gem/ruby/1.9.1/gems/infoblox-0.4.0/lib/infoblox/connection.rb:17:in `block in get'
        from /app/app/home/gemtest/.gem/ruby/1.9.1/gems/infoblox-0.4.0/lib/infoblox/connection.rb:80:in `wrap'
        from /app/app/home/gemtest/.gem/ruby/1.9.1/gems/infoblox-0.4.0/lib/infoblox/connection.rb:16:in `get'
        from /app/app/home/gemtest/.gem/ruby/1.9.1/gems/infoblox-0.4.0/lib/infoblox/resource.rb:106:in `find'
        from (irb):5
        from /opt/rh/ruby193/root/usr/bin/irb:12:in `<main>'
```

```
Faraday::ConnectionFailed: 403 "Forbidden"
        from /usr/lib/ruby/1.8/net/http.rb:2105:in `error!'
        from /usr/lib/ruby/1.8/net/http.rb:2114:in `value'
        from /usr/lib/ruby/1.8/net/http.rb:584:in `connect'
        from /usr/lib/ruby/1.8/net/http.rb:553:in `do_start'
        from /usr/lib/ruby/1.8/net/http.rb:542:in `start'
        from /usr/lib/ruby/1.8/net/http.rb:1035:in `request'
        from /usr/lib/ruby/1.8/net/http.rb:772:in `get'
        from /usr/lib/ruby/gems/1.8/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:80:in `perform_request'
        from /usr/lib/ruby/gems/1.8/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `call'
        from /usr/lib/ruby/gems/1.8/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
        from /usr/lib/ruby/gems/1.8/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
        from /usr/lib/ruby/gems/1.8/gems/faraday_middleware-0.9.1/lib/faraday_middleware/request/encode_json.rb:23:in `call'
        from /usr/lib/ruby/gems/1.8/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
        from /usr/lib/ruby/gems/1.8/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
        from /usr/lib/ruby/gems/1.8/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
        from /usr/lib/ruby/gems/1.8/gems/infoblox-0.4.0/lib/infoblox/connection.rb:17:in `get'
        from /usr/lib/ruby/gems/1.8/gems/infoblox-0.4.0/lib/infoblox/connection.rb:80:in `wrap'
        from /usr/lib/ruby/gems/1.8/gems/infoblox-0.4.0/lib/infoblox/connection.rb:16:in `get'
        from /usr/lib/ruby/gems/1.8/gems/infoblox-0.4.0/lib/infoblox/resource.rb:106:in `find'
        from (irb):8
        from :0
```

It works with the old version :)

**Comment by Klaas-** [comment]
just for reference what I'm doing on both ruby versions:
connection = Infoblox::Connection.new(:username => 'admin', :password => 'password', :host => 'https://url')
host = Infoblox::HostIpv4addr.find(connection, {"ipv4addr" => "192.168.0.1"}).first

**Comment by unclebilly** [comment]
Strange... I cannot reproduce this error. Nor does it seem like this would be a result of the changes I made for 1.8.7 compatibility, but I could be wrong.  
Are you sure there isn't a misconfiguration on your end?  Are you able to log into the Infoblox appliance's user interface? 

If you continue to see the problem, can you retry using a logger on STDOUT, and then paste the output? Like this: 
```
    connection = Infoblox::Connection.new(
      :username => 'admin', 
      :password => 'password', 
      :host => 'https://url', 
      :logger => Logger.new(STDOUT))
```

Be sure to remove the "Authorization:" output before pasting it here if you do this!

**Comment by Klaas-** [comment]
I think I fucked up :) thats a response of the proxy I had to use to get the new gem ... :D sorry about that

**Comment by unclebilly** [comment]
:relieved:
